name: CI

on:
  workflow_dispatch:  # Manual trigger
  #push:              # Automatic trigger
  #  branches: [ main ]
  

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5   

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: uv venv .venv

      - name: Add venv to PATH
        run: echo "$(pwd)/.venv/bin" >> $GITHUB_PATH

      - name: Install dependencies (uv sync)
        run: uv sync

      - name: Install dependencies (uv sync)
        run: uv sync

      - name: Install project itself (editable)
        run: uv pip install -e .

      - name: Lint (ruff)
        run: ruff check

      - name: Type-check
        run: ty check

      - name: Dependency check
        run: deptry .

      - name: Run tests
        run: pytest

      - name: Build docs
        run: mkdocs build
